language: python
services:
  - mysql
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codacy-coverage
before_script:
  - mysql -u root -e 'CREATE DATABASE treeD;'
  - mysql -u root -e "CREATE USER 'usuario'@'localhost' IDENTIFIED BY 'usuario';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON * . * TO 'usuario'@'localhost';"
  - cd treeD
script:
  - coverage run --source='.' manage.py test
  - coverage xml
after_success:
  - python-codacy-coverage -r coverage.xml
