language: python
services:
  - postgresql
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codacy-coverage
before_script:
  - psql -U postgres -c "create user usuario password 'usuario'"
  - psql -U postgres -c "create database treeD owner usuario"
  - psql -U postgres -c "ALTER USER usuario CREATEDB"
  - cd treeD
script:
  - coverage run --source='.' manage.py test
  - coverage xml
after_success:
  - python-codacy-coverage -r coverage.xml
