# Generated by Django 3.0.3 on 2020-03-06 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True, verbose_name='Categoría')),
            ],
            options={
                'ordering': ('idCategoria',),
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.AutoField(primary_key=True, serialize=False)),
                ('fechaDeCompra', models.DateField(verbose_name='Fecha de compra')),
            ],
            options={
                'ordering': ('idCompra', 'fechaDeCompra'),
            },
        ),
        migrations.CreateModel(
            name='Impresion',
            fields=[
                ('idImpresion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('categorias', models.ManyToManyField(to='main.Categoria')),
            ],
            options={
                'ordering': ('idImpresion',),
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idPerfil', models.AutoField(primary_key=True, serialize=False)),
                ('impresionesCompradas', models.ManyToManyField(blank=True, through='main.Compra', to='main.Impresion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('idPerfil',),
            },
        ),
        migrations.AddField(
            model_name='impresion',
            name='publicador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Perfil'),
        ),
        migrations.AddField(
            model_name='compra',
            name='idImpresion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Impresion'),
        ),
        migrations.AddField(
            model_name='compra',
            name='idPerfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Perfil'),
        ),
    ]
