# Generated by Django 3.0.3 on 2020-03-06 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.AutoField(primary_key=True, serialize=False)),
                ('fechaDeCompra', models.DateField(verbose_name='Fecha de compra')),
            ],
            options={
                'ordering': ('idCompra', 'fechaDeCompra'),
            },
        ),
        migrations.AlterField(
            model_name='impresion',
            name='precio',
            field=models.FloatField(verbose_name='Precio'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idPerfil', models.AutoField(primary_key=True, serialize=False)),
                ('impresionesCompradas', models.ManyToManyField(blank=True, through='main.Compra', to='main.Impresion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('idPerfil',),
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='idImpresion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Impresion'),
        ),
        migrations.AddField(
            model_name='compra',
            name='idPerfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Perfil'),
        ),
        migrations.AlterField(
            model_name='impresion',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Perfil'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
