# Generated by Django 3.0.3 on 2020-04-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direcperfil',
            name='direccion',
        ),
        migrations.AddField(
            model_name='direcperfil',
            name='calle',
            field=models.TextField(default='C/', verbose_name='Calle o avenida'),
        ),
        migrations.AddField(
            model_name='direcperfil',
            name='ciudad',
            field=models.TextField(default='Sevilla', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='direcperfil',
            name='codigo_postal',
            field=models.TextField(default='41008', verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='direcperfil',
            name='localidad',
            field=models.TextField(default='Sevilla', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='direcperfil',
            name='numero',
            field=models.TextField(default='Nº27 2ºIzq', verbose_name='Portal y número'),
        ),
    ]
