# Generated by Django 3.0.3 on 2020-03-21 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.DirecPerfil'),
        ),
        migrations.CreateModel(
            name='ImgPrueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Compra')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
