# Generated by Django 3.0.3 on 2020-03-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('idCategoria',)},
        ),
    ]
