# Generated by Django 3.0.3 on 2020-03-06 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.TextField(verbose_name='Categoría')),
            ],
            options={
                'ordering': ('categoria',),
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('idImagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('impresion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Impresion')),
            ],
            options={
                'ordering': ('idImagen',),
            },
        ),
        migrations.AddField(
            model_name='impresion',
            name='categorias',
            field=models.ManyToManyField(to='main.Categoria'),
        ),
    ]
