# Generated by Django 3.0.3 on 2020-03-15 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('idCategoria',)},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='idImpresion',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='idPerfil',
        ),
        migrations.RemoveField(
            model_name='impresion',
            name='publicador',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='impresionesCompradas',
        ),
        migrations.AddField(
            model_name='compra',
            name='comprador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprador', to='main.Perfil'),
        ),
        migrations.AddField(
            model_name='compra',
            name='descripcionImpresion',
            field=models.TextField(blank=True, verbose_name='Descripción de la impresión'),
        ),
        migrations.AddField(
            model_name='compra',
            name='nombreImpresion',
            field=models.TextField(blank=True, verbose_name='Nombre de la impresión'),
        ),
        migrations.AddField(
            model_name='compra',
            name='precioImpresion',
            field=models.FloatField(null=True, verbose_name='Precio de la impresión'),
        ),
        migrations.AddField(
            model_name='compra',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedor', to='main.Perfil'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Compra'),
        ),
        migrations.AddField(
            model_name='impresion',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Perfil'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='imagenes', verbose_name='Imagen'),
        ),
    ]
