# Generated by Django 3.0.3 on 2020-04-11 14:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota')),
                ('opinion', models.TextField(verbose_name='Opinion')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Compra', to='main.Compra')),
                ('puntuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Puntuador', to='main.Perfil')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
