# Generated by Django 3.0.3 on 2020-03-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impresion',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
