# Generated by Django 3.0.3 on 2020-04-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='tamaño',
            field=models.TextField(null=True, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='tamaño',
            field=models.TextField(null=True, verbose_name='Tamaño'),
        ),
    ]
