# Generated by Django 3.0.3 on 2020-03-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200306_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impresion',
            old_name='vendedor',
            new_name='publicador',
        ),
    ]
