# Generated by Django 3.0.3 on 2020-03-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200306_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True, verbose_name='Categoría')),
            ],
            options={
                'ordering': ('idCategoria',),
            },
        ),
        migrations.AddField(
            model_name='impresion',
            name='categorias',
            field=models.ManyToManyField(to='main.Categoria'),
        ),
    ]
