# Generated by Django 3.0.3 on 2020-03-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200316_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='imagenes',
            field=models.ManyToManyField(to='main.Imagen'),
        ),
    ]
