# Generated by Django 3.0.3 on 2020-04-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200412_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcperfil',
            name='calle',
            field=models.TextField(verbose_name='Calle o avenida'),
        ),
        migrations.AlterField(
            model_name='direcperfil',
            name='ciudad',
            field=models.TextField(verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='direcperfil',
            name='codigo_postal',
            field=models.TextField(verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='direcperfil',
            name='localidad',
            field=models.TextField(verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='direcperfil',
            name='numero',
            field=models.TextField(verbose_name='Portal y número'),
        ),
    ]
