# Generated by Django 3.0.3 on 2020-04-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200419_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoenvio',
            name='codigo_envio',
            field=models.TextField(null=True, verbose_name='Código de envío'),
        ),
    ]
