# Generated by Django 3.0.3 on 2020-03-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200306_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='impresionesCompradas',
        ),
    ]
