# Generated by Django 3.0.3 on 2020-03-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200307_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresion',
            name='categorias',
            field=models.ManyToManyField(to='main.Categoria'),
        ),
    ]
