# Generated by Django 3.0.3 on 2020-04-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200412_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcperfil',
            name='numero',
            field=models.TextField(verbose_name='número'),
        ),
    ]
