# Generated by Django 3.0.3 on 2020-04-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200419_2205'),
        ('main', '0003_auto_20200419_1838'),
    ]

    operations = [
    ]
