# Generated by Django 3.0.3 on 2020-03-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200320_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
