# Generated by Django 3.0.3 on 2020-04-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200412_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email_paypal',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email de Paypal'),
        ),
    ]
