# Generated by Django 3.0.3 on 2020-03-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200320_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(default='default.png', upload_to='', verbose_name='Imagen'),
        ),
    ]
