# Generated by Django 3.0.3 on 2020-03-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200306_1538'),
        ('main', '0003_auto_20200306_1338'),
    ]

    operations = [
    ]
