# Generated by Django 3.0.3 on 2020-04-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200412_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgprueba',
            name='codigo_envio',
            field=models.TextField(default='codigo', null=True, verbose_name='Código de envío'),
        ),
        migrations.AddField(
            model_name='imgprueba',
            name='empresa_envio',
            field=models.TextField(default='empresa', verbose_name='Empresa del envío'),
        ),
    ]
