# Generated by Django 3.0.3 on 2020-04-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200417_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgprueba',
            name='codigo_envio',
            field=models.TextField(null=True, verbose_name='Código de envío'),
        ),
        migrations.AlterField(
            model_name='imgprueba',
            name='empresa_envio',
            field=models.TextField(verbose_name='Empresa del envío'),
        ),
    ]
