# Generated by Django 3.0.3 on 2020-03-15 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200307_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='idImpresion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='impresionesCompradas',
        ),
        migrations.AddField(
            model_name='compra',
            name='descripcionImpresion',
            field=models.TextField(blank=True, verbose_name='Descripción de la impresión'),
        ),
        migrations.AddField(
            model_name='compra',
            name='nombreImpresion',
            field=models.TextField(blank=True, verbose_name='Nombre de la impresión'),
        ),
        migrations.AddField(
            model_name='compra',
            name='precioImpresion',
            field=models.FloatField(null=True, verbose_name='Precio de la impresión'),
        ),
        migrations.AlterField(
            model_name='impresion',
            name='publicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Perfil'),
        ),
    ]
