# Generated by Django 3.0.3 on 2020-03-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200320_1902'),
        ('main', '0002_auto_20200321_2029'),
    ]

    operations = [
    ]
