# Generated by Django 3.0.3 on 2020-04-17 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200417_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgprueba',
            name='codigo_envio',
        ),
        migrations.RemoveField(
            model_name='imgprueba',
            name='empresa_envio',
        ),
        migrations.CreateModel(
            name='CodigoEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_envio', models.TextField(verbose_name='Código de envío')),
                ('empresa_envio', models.TextField(verbose_name='Empresa del envío')),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Compra')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
