# Generated by Django 3.0.3 on 2020-04-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_perfil_email_paypal'),
        ('main', '0007_auto_20200417_1642'),
    ]

    operations = [
    ]
