# Generated by Django 3.0.3 on 2020-04-02 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('apellidos', models.TextField(verbose_name='Apellidos')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('imagen', models.ImageField(default='default.png', upload_to='', verbose_name='Imagen')),
                ('es_afiliado', models.BooleanField(verbose_name='Afiliado?')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='DirecPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
